### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by hackhowtofaq** [anilmaurya/fast_jsonparser#18]
There is definitely a memory leak.

I replaced Oj with this gem and the memory consumption after 3 hours was insane.

I' ll try to pint point the issue.

Thanks

**Comment by anilmaurya** [comment]
Hi @hackhowtofaq 
Did you figure out where the issue is ?

**Comment by hackhowtofaq** [comment]
I am not sure if the problem was the gem or eventmachine, so I will close the issue. Regards
