### ISSUE TITLE
Streaming support?

### ISSUE THREAD

**Issue by thbar** [anilmaurya/fast_jsonparser#2]
I just discovered this gem. Congrats, this seems very useful!

I wonder if you will (or already) support streaming processing of large files, either newline delimited files, or just large files?

Thanks!

**Comment by anilmaurya** [comment]
Hi @thbar 

This gem is wrapper over https://github.com/simdjson/simdjson, simdjson does not support streaming directly.
I will check how to do it. would you like to help ?

**Comment by thbar** [comment]
I just had a little look at the documentation. In particular this seems interesting:

https://github.com/simdjson/simdjson/blob/master/doc/basics.md#newline-delimited-json-ndjson-and-json-lines

I do not have a strong need yet, but I will update you if the strong need comes, in which case I'll be happy to help!

**Comment by anilmaurya** [comment]
Hi @thbar 
I just release `0.3.0` with file streaming support, have a look at it.

**Comment by thbar** [comment]
Hi @anilmaurya - thank you for your work! Amazing. I will try it out. Closing this issue!
