### ISSUE TITLE
Symbol keys

### ISSUE THREAD

**Issue by StefanoMartin** [anilmaurya/fast_jsonparser#3]
This gem is really interesting.

I noticed that it does not seems to have an option for "symbol_keys" (having symbols for hash keys).
Do you plan to have it in the future?

**Comment by anilmaurya** [comment]
Hi @StefanoMartin 

Thank you for your interest.
This gem parses JSON data only, parsing ruby hash is not supported.

**Comment by noteflakes** [comment]
I think the OP meant having the parsed result with symbols keys...

**Comment by anilmaurya** [comment]
Hi @ciconia 
Thanks for clarification. It make sense to have symbol keys for parsed result.

I release 0.2.0 with symbol keys.

**Comment by StefanoMartin** [comment]
That sounds great! Thank you!
